---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: client
  namespace: schlep
  labels:
    app: schlep
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schlep
      role: client
  template:
    metadata:
      labels:
        app: schlep
        role: client
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: main
          image: ghcr.io/olix0r/schlep:v0.3.7
          args:
            - client
            - --rate=1000
            - schlep:80
...
