---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-http
  namespace: schlep
  labels:
    app: schlep
    role: client
    proto: http
spec:
  replicas: 0
  selector:
    matchLabels:
      app: schlep
      role: client
      proto: http
  template:
    metadata:
      labels:
        app: schlep
        role: client
        proto: http
      annotations:
        # linkerd.io/inject: enabled
        # config.linkerd.io/proxy-log-level: linkerd=debug,h2=debug,info
        # config.linkerd.io/proxy-log-http-headers: insecure
    spec:
      containers:
        - name: main
          image: ghcr.io/olix0r/schlep:v0.5.3
          args:
            - client
            - --rate=1
            - api:80
...
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-grpc
  namespace: schlep
  labels:
    app: schlep
    role: client
    proto: grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schlep
      role: client
      proto: grpc
  template:
    metadata:
      labels:
        app: schlep
        role: client
        proto: grpc
      annotations:
        # linkerd.io/inject: enabled
        # config.linkerd.io/proxy-log-level: linkerd=debug,h2=debug,info
        # config.linkerd.io/proxy-log-http-headers: insecure
    spec:
      containers:
        - name: main
          image: ghcr.io/olix0r/schlep:v0.5.3
          args:
            - client
            - --grpc
            - --rate=0.01
            - --sink
            - --sink-lifetime=300,600,3600
            - --data=1000000,10000000,4000000
            - --sleep=1,10,100
            - api:8080
...
