---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: schlep-default
  namespace: schlep
  annotations:
    retry.linkerd.io/http: 5xx
    retry.linkerd.io/limit: "2"
    retry.linkerd.io/timeout: 80ms
    timeout.linkerd.io/idle: 200ms
    timeout.linkerd.io/response: 200ms
    timeout.linkerd.io/stream: 200ms
spec:
  parentRefs:
    - name: schlep
      kind: Service
      group: core
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
...
