---
kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: schlep
  labels:
    app: schlep
    role: server
  # annotations:
  #   balancer.linkerd.io/failure-accrual: "consecutive"
  #   balancer.linkerd.io/failure-accrual-consecutive-max-failures: "3"
spec:
  type: LoadBalancer
  selector:
    app: schlep
    role: server
  ports:
    - name: http
      appProtocol: kubernetes.io/h2c
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      appProtocol: kubernetes.io/h2c
      protocol: TCP
      port: 8080
      targetPort: 8080
...
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: server
  namespace: schlep
  labels:
    app: schlep
data:
  okay.json: |
    {
      "sleep": {
        "min": 0.001,
        "p50": 0.01,
        "p90": 0.1,
        "p99": 0.3,
        "max": 0.5,
      },
      "data": {
        "min": 5,
        "p50": 500,
        "p90": 5000,
        "p99": 50000,
        "max": 50000,
      }
    }
  fail.json: |
    {
      "h2-stream-reset": 3,
    }
  slow.json: |
    {
      "sleep": {
        "min": 0.1,
        "p50": 1.0,
        "p90": 10.0,
        "p99": 30.0,
        "max": 60.0,
      },
      "data": {
        "min": 5,
        "p50": 500,
        "p90": 5000,
        "p99": 50000,
        "max": 50000,
      }
    }
...
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: server-okay
  namespace: schlep
  labels:
    app: schlep
    role: server
    flavor: okay
spec:
  replicas: 0
  selector:
    matchLabels:
      app: schlep
      role: server
      flavor: okay
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-log-level: 'h2::proto::streams::prioritize[name=\"inbound\"]=trace,info'
        config.linkerd.io/proxy-log-format: json
      labels:
        app: schlep
        role: server
        flavor: okay
    spec:
      containers:
        - name: main
          image: ghcr.io/olix0r/schlep:v0.5.3
          args:
            - server
            - --config=/okay.json
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /okay.json
              subPath: okay.json
      volumes:
        - name: config
          configMap:
            name: server
            items:
              - key: okay.json
                path: okay.json
...
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: server-fail
  namespace: schlep
  labels:
    app: schlep
    role: server
    flavor: fail
spec:
  replicas: 0
  selector:
    matchLabels:
      app: schlep
      role: server
      flavor: fail
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-log-level: h2[inbound]=trace,info
        config.linkerd.io/proxy-log-format: json
      labels:
        app: schlep
        role: server
        flavor: fail
    spec:
      containers:
        - name: main
          image: ghcr.io/olix0r/schlep:v0.5.3
          args:
            - server
            - --config=/fail.json
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /fail.json
              subPath: fail.json
      volumes:
        - name: config
          configMap:
            name: server
            items:
              - key: fail.json
                path: fail.json
...
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: server-slow
  namespace: schlep
  labels:
    app: schlep
    role: server
    flavor: slow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schlep
      role: server
      flavor: slow
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-log-level: h2[inbound]=trace,linkerd=debug,info
        config.linkerd.io/proxy-log-format: json
      labels:
        app: schlep
        role: server
        flavor: slow
    spec:
      containers:
        - name: main
          image: ghcr.io/olix0r/schlep:v0.5.3
          args:
            - --log=schlep=debug,info
            - --log-format=json
            - server
            - --config=/slow.json
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /slow.json
              subPath: slow.json
      volumes:
        - name: config
          configMap:
            name: server
            items:
              - key: slow.json
                path: slow.json
