---
# Equivalent to the schlep-default route
kind: ServiceProfile
apiVersion: linkerd.io/v1alpha2
metadata:
  name: schlep.schlep.svc.cluster.local
  namespace: schlep
spec:
  routes:
    - name: GET /
      condition:
        method: GET
        pathRegex: /
      isRetryable: true
      timeout: 2s
...
